# Generated by Django 5.2.3 on 2025-06-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='require_order',
            field=models.BooleanField(default=False),
        ),
    ]
