# Generated by Django 5.2.3 on 2025-06-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_require_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_fill_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=20),
        ),
    ]
