# Generated by Django 5.2.3 on 2025-06-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_is_fill_in_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='Python', max_length=50),
        ),
    ]
