# Generated by Django 5.2.3 on 2025-06-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_e',
            field=models.TextField(default='X'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_f',
            field=models.TextField(default='X'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_g',
            field=models.TextField(default='X'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_h',
            field=models.TextField(default='X'),
        ),
    ]
