# Generated by Django 5.2.3 on 2025-06-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_choice_e_question_choice_f_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='fill_answer',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
