# Generated by Django 5.2.3 on 2025-07-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_questionrecord_session_key_alter_questionrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
