# Generated by Django 5.2.3 on 2025-07-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_question_ai_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ai_explanation',
        ),
        migrations.AddField(
            model_name='questionrecord',
            name='ai_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
