# Generated by Django 5.2.3 on 2025-07-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_question_ai_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionrecord',
            name='source',
            field=models.CharField(choices=[('mock', '隨機測驗'), ('chapter', '章節練習')], default='mock', max_length=20),
        ),
    ]
