# Generated by Django 5.2.3 on 2025-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_questionrecord_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number_order',
            field=models.FloatField(default=0),
        ),
    ]
