# Generated by Django 5.2.3 on 2025-07-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number_order',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
