# Generated by Django 5.2.3 on 2025-07-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_remove_userprofile_bio_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_e',
            field=models.TextField(default='`X`'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_f',
            field=models.TextField(default='`X`'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_g',
            field=models.TextField(default='`X`'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_h',
            field=models.TextField(default='`X`'),
        ),
    ]
