# Generated by Django 5.2.3 on 2025-07-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_questionbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionrecord',
            name='shuffled_choices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
