# Generated by Django 5.2.3 on 2025-07-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_questionrecord_shuffled_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionrecord',
            name='shuffled_correct_answer',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
