# Generated by Django 5.2.3 on 2025-07-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_questionrecord_shuffled_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbookmark',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
